name: macOS
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install nix
        uses: cachix/install-nix-action@v13
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: trevorite
          signingKey: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nix packages
        run: nix-build . -A erlang -A elixir
        env:
          NIXPKGS_ALLOW_INSECURE: 1
